name: test action

on:
  push:
  pull_request:

jobs:
  test_actism: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with: 
          node-version: '20'
      - run: node tests.js
  
  ci_example_pipelines:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: actism-image
        with:
          wasi: true
          input: "this is a test"
          output_type: text
          steps: |- # line-delimited set of named plugin calls, where "step()" export is ran
            count vowels | https://github.com/extism/plugins/releases/latest/download/count_vowels.wasm | count_vowels
            convert output to image data | https://cdn.modsurfer.dylibso.com/api/v1/module/271d6599df5fc1c54ddc33c266840123636d2c886e5064a739324f92ae8fc5ac.wasm
            generate png | https://cdn.modsurfer.dylibso.com/api/v1/module/2c9eb901052b1e6397d2414bdb796975407cc87085e6b5fe9564932538d8af51.wasm | handle
      - name: check output
        run: |
          echo '${{steps.actism-image.outputs.output}}' | jq '.value' | base64 -d -i > out.png
      - uses: actions/upload-artifact@v4
        with:
          name: out.png
          path: ./out.png

      - uses: ./
        id: actism-text
        with:
          wasi: true
          input: "this is a test"
          output_type: text
          steps: |- # line-delimited set of named plugin calls, where "step()" export is ran
            count vowels | https://github.com/extism/plugins/releases/latest/download/count_vowels.wasm | count_vowels
      - name: check output
        run: |
          echo '${{steps.actism-text.outputs.output}}' | grep '"count":4'